apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30081  # 원하는 NodePort로 설정
