spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service  # Kubernetes ??? ??? ??
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service  # Kubernetes ??? ??? ??
          predicates:
            - Path=/payments/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Spring Cloud Gateway? ??? ?? ???
    org.springframework.web: DEBUG            # ? ?? ??/?? ??? ??
    org.springframework.http: DEBUG           # HTTP ??/?? ??? ??
