spring:
  application:
    name: payment-service

  rabbitmq:
    host: my-rabbitmq  # Kubernetes??? RabbitMQ ??? ??
    port: 5672
    username: user  # Helm ?? ? ??? ?? ??? ??
    password: nRrTCBnMRmwcrF5z  # Helm ?? ? ??? ?? ????

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://10.108.69.72:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  rabbitmq:
    queue: order-queue
    exchange: order-exchange
    routing-key: order-routing-key
